- name: Launch front
  community.docker.docker_container:
    name: front
    image: victor7934/tp-devops-front:latest
    networks:
      - name: proxy-network
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python