all:
  vars:
    ansible_user: admin
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_python_interpreter: /usr/bin/python3.11
    POSTGRES_DB: "db"
    POSTGRES_USER: "usr"
    POSTGRES_PASSWORD: "pwd"
    BACKEND_HOST: "my-backend"
    BACKEND_PORT: "8080"
  children:
    prod:
      hosts:
        victor.eymard.takima.school:
