name: CD

on:
  workflow_run:
    workflows:
      - CI
    branches:
      - main
    types:
      - completed

jobs:
  push-backend:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build and push backend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest ./TP1_docker/backend2/simpleapi
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest

  push-database:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build and push database
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest ./TP1_docker/sql
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest

  push-httpd:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build and push httpd
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest ./TP1_docker/http
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest

  push-front:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build image and push front
        uses: docker/build-push-action@v6
        with:
          context: ./devops-front-main/devops-front-main
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-front:latest
          push: true